function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},w;
if("function"==typeof Object.setPrototypeOf)w=Object.setPrototypeOf;else{var A;a:{var ea={M:!0},B={};try{B.__proto__=ea;A=B.M;break a}catch(a){}A=!1}w=A?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var D=w;function fa(){}var E={},F=[],ha=[];
function H(a,b){var c=ha,e,d;for(d=arguments.length;2<d--;)F.push(arguments[d]);b&&null!=b.children&&(F.length||F.push(b.children),delete b.children);for(;F.length;)if((e=F.pop())&&void 0!==e.pop)for(d=e.length;d--;)F.push(e[d]);else{"boolean"===typeof e&&(e=null);if(d="function"!==typeof a)null==e?e="":"number"===typeof e?e=String(e):"string"!==typeof e&&(d=!1);d&&f?c[c.length-1]+=e:c===ha?c=[e]:c.push(e);var f=d}f=new fa;f.nodeName=a;f.children=c;f.attributes=null==b?void 0:b;f.key=null==b?void 0:
b.key;void 0!==E.ba&&E.ba(f);return f}function I(a,b){for(var c in b)a[c]=b[c];return a}function J(a,b){a&&("function"==typeof a?a(b):a.current=b)}var ia="function"==typeof Promise?Promise.resolve().then.bind(Promise.resolve()):setTimeout,ja=/acit|ex(?:s|g|n|p|$)|rph|ows|mnc|ntw|ine[ch]|zoo|^ord/i,ka=[];function la(a){!a.j&&(a.j=!0)&&1==ka.push(a)&&(E.fa||ia)(ma)}function ma(){for(var a;a=ka.pop();)a.j&&K(a)}
function na(a){var b=I({},a.attributes);b.children=a.children;a=a.nodeName.ga;if(void 0!==a)for(var c in a)void 0===b[c]&&(b[c]=a[c]);return b}function L(a){var b=a.parentNode;b&&b.removeChild(a)}
function oa(a,b,c,e){var d=M;"className"===b&&(b="class");if("key"!==b)if("ref"===b)J(c,null),J(e,a);else if("class"!==b||d)if("style"===b){if(e&&"string"!==typeof e&&"string"!==typeof c||(a.style.cssText=e||""),e&&"object"===typeof e){if("string"!==typeof c)for(var f in c)f in e||(a.style[f]="");for(f in e)a.style[f]="number"===typeof e[f]&&!1===ja.test(f)?e[f]+"px":e[f]}}else if("dangerouslySetInnerHTML"===b)e&&(a.innerHTML=e.da||"");else if("o"==b[0]&&"n"==b[1])d=b!==(b=b.replace(/Capture$/,"")),
b=b.toLowerCase().substring(2),e?c||a.addEventListener(b,pa,d):a.removeEventListener(b,pa,d),(a.F||(a.F={}))[b]=e;else if("list"!==b&&"type"!==b&&!d&&b in a){try{a[b]=null==e?"":e}catch(h){}null!=e&&!1!==e||"spellcheck"==b||a.removeAttribute(b)}else c=d&&b!==(b=b.replace(/^xlink:?/,"")),null==e||!1===e?c?a.removeAttributeNS("http://www.w3.org/1999/xlink",b.toLowerCase()):a.removeAttribute(b):"function"!==typeof e&&(c?a.setAttributeNS("http://www.w3.org/1999/xlink",b.toLowerCase(),e):a.setAttribute(b,
e));else a.className=e||""}function pa(a){return this.F[a.type](E.event&&E.event(a)||a)}var qa=[],N=0,M=!1,O=!1;function ra(){for(var a;a=qa.shift();)E.N&&E.N(a),a.H&&a.H()}function sa(a,b,c,e,d,f){N++||(M=null!=d&&void 0!==d.ka,O=null!=a&&!("__preactattr_"in a));a=ta(a,b,c,e,f);d&&a.parentNode!==d&&d.appendChild(a);--N||(O=!1,f||ra());return a}
function ta(a,b,c,e,d){var f=a,h=M;if(null==b||"boolean"===typeof b)b="";if("string"===typeof b||"number"===typeof b)return a&&void 0!==a.splitText&&a.parentNode&&(!a.a||d)?a.nodeValue!=b&&(a.nodeValue=b):(f=document.createTextNode(b),a&&(a.parentNode&&a.parentNode.replaceChild(f,a),P(a,!0))),f.__preactattr_=!0,f;d=b.nodeName;if("function"===typeof d){h=a;var g=b;f=b=h&&h.a;var r=h,p=b&&h.s===g.nodeName,m=p;for(a=na(g);b&&!m&&(b=b.G);)m=b.constructor===g.nodeName;b&&m&&(!e||b.a)?(Q(b,a,3,c,e),h=b.c):
(f&&!p&&(R(f),h=r=null),b=ua(g.nodeName,a,c),h&&!b.f&&(b.f=h,r=null),Q(b,a,1,c,e),h=b.c,r&&h!==r&&(r.a=null,P(r,!1)));return h}M="svg"===d?!0:"foreignObject"===d?!1:M;d=String(d);if(!a||a.K!==d&&a.nodeName.toLowerCase()!==d.toLowerCase())if(f=d,d=M?document.createElementNS("http://www.w3.org/2000/svg",f):document.createElement(f),d.K=f,f=d,a){for(;a.firstChild;)f.appendChild(a.firstChild);a.parentNode&&a.parentNode.replaceChild(f,a);P(a,!0)}var n=f.firstChild;a=f.__preactattr_;d=b.children;if(null==
a){a=f.__preactattr_={};for(var k=f.attributes,v=k.length;v--;)a[k[v].name]=k[v].value}if(!O&&d&&1===d.length&&"string"===typeof d[0]&&null!=n&&void 0!==n.splitText&&null==n.nextSibling)n.nodeValue!=d[0]&&(n.nodeValue=d[0]);else if(d&&d.length||null!=n){n=f;k=O||null!=a.ea;v=n.childNodes;var x=[],z={},t=0,q=0,l=v.length,G=0,X=d?d.length:0;if(0!==l)for(m=0;m<l;m++){var u=v[m],C=u.__preactattr_;var y=X&&C?u.a?u.a.C:C.key:null;if(null!=y)t++,z[y]=u;else if(C||(void 0!==u.splitText?k?u.nodeValue.trim():
1:k))x[G++]=u}if(0!==X)for(m=0;m<X;m++){l=d[m];p=null;y=l.key;if(null!=y)t&&void 0!==z[y]&&(p=z[y],z[y]=void 0,t--);else if(q<G)for(y=q;y<G;y++){if(u=void 0!==x[y])if(u=r=x[y],"string"===typeof l||"number"===typeof l)u=void 0!==u.splitText;else if("string"===typeof l.nodeName){if(C=!u.s)C=l.nodeName,C=u.K===C||u.nodeName.toLowerCase()===C.toLowerCase();u=C}else u=k||u.s===l.nodeName;if(u){p=r;x[y]=void 0;y===G-1&&G--;y===q&&q++;break}}p=ta(p,l,c,e);l=v[m];p&&p!==n&&p!==l&&(null==l?n.appendChild(p):
p===l.nextSibling?L(l):n.insertBefore(p,l))}if(t)for(m in z)void 0!==z[m]&&P(z[m],!1);for(;q<=G;)void 0!==(p=x[G--])&&P(p,!1)}c=f;e=b.attributes;b=a;for(g in b)e&&null!=e[g]||null==b[g]||oa(c,g,b[g],b[g]=void 0);for(g in e)"children"===g||"innerHTML"===g||g in b&&e[g]===("value"===g||"checked"===g?c[g]:b[g])||oa(c,g,b[g],b[g]=e[g]);M=h;return f}function P(a,b){var c=a.a;c?R(c):(null!=a.__preactattr_&&J(a.__preactattr_.B,null),!1!==b&&null!=a.__preactattr_||L(a),va(a))}
function va(a){for(a=a.lastChild;a;){var b=a.previousSibling;P(a,!0);a=b}}var S=[];function ua(a,b,c){var e=S.length;if(a.prototype&&a.prototype.o){var d=new a(b,c);T.call(d,b,c)}else d=new T(b,c),d.constructor=a,d.o=wa;for(;e--;)if(S[e].constructor===a){d.f=S[e].f;S.splice(e,1);break}return d}function wa(a,b,c){return this.constructor(a,c)}
function Q(a,b,c,e,d){a.l||(a.l=!0,a.D=b.B,a.C=b.key,delete b.B,delete b.key,"undefined"===typeof a.constructor.J&&(!a.c||d?a.S&&a.S():a.T&&a.T(b,e)),e&&e!==a.context&&(a.v||(a.v=a.context),a.context=e),a.w||(a.w=a.b),a.b=b,a.l=!1,0!==c&&(1!==c&&!1===E.ma&&a.c?la(a):K(a,1,d)),J(a.D,a))}
function K(a,b,c,e){if(!a.l){var d=a.b,f=a.state,h=a.context,g=a.w||d,r=a.A||f,p=a.v||h,m=a.c,n=a.f,k=m||n,v=a.a,x=!1,z=p,t;a.constructor.J&&(f=I(I({},f),a.constructor.J(d,f)),a.state=f);m&&(a.b=g,a.state=r,a.context=p,2!==b&&a.Z&&!1===a.Z(d,f,h)?x=!0:a.U&&a.U(d,f,h),a.b=d,a.state=f,a.context=h);a.w=a.A=a.v=a.f=null;a.j=!1;if(!x){d=a.o(d,f,h);a.X&&(h=I(I({},h),a.X()));m&&a.Y&&(z=a.Y(g,r));f=d&&d.nodeName;if("function"===typeof f){var q=na(d);if((t=v)&&t.constructor===f&&q.key==t.C)Q(t,q,1,h,!1);else{var l=
t;a.a=t=ua(f,q,h);t.f=t.f||n;t.G=a;Q(t,q,0,h,!1);K(t,1,c,!0)}q=t.c}else{n=k;if(l=v)n=a.a=null;if(k||1===b)n&&(n.a=null),q=sa(n,d,h,c||!m,k&&k.parentNode,!0)}k&&q!==k&&t!==v&&(h=k.parentNode)&&q!==h&&(h.replaceChild(q,k),l||(k.a=null,P(k,!1)));l&&R(l);if((a.c=q)&&!e){for(l=k=a;l=l.G;)(k=l).c=q;q.a=k;q.s=k.constructor}}!m||c?qa.push(a):x||(a.R&&a.R(g,r,z),E.O&&E.O(a));for(;a.m.length;)a.m.pop().call(a);N||e||ra()}}
function R(a){E.P&&E.P(a);var b=a.c;a.l=!0;a.I&&a.I();a.c=null;var c=a.a;c?R(c):b&&(null!=b.__preactattr_&&J(b.__preactattr_.B,null),a.f=b,L(b),S.push(a),va(b));J(a.D,null)}function T(a,b){this.j=!0;this.context=b;this.b=a;this.state=this.state||{};this.m=[]}I(T.prototype,{i:function(a,b){this.A||(this.A=this.state);this.state=I(I({},this.state),"function"===typeof a?a(this.state,this.b):a);b&&this.m.push(b);la(this)},ia:function(a){a&&this.m.push(a);K(this,2)},o:function(){}});function xa(a){var b=void 0===b?{}:b;var c=window.top,e=c.outerHeight,d=c.screenY,f=[];f.push("width=500","left="+(c.outerWidth/2+c.screenX-250));f.push("top="+(e/2+d-305-50),"height=610");c=Object.keys(b).map(function(h){return h+"="+b[h]});f.push.apply(f,c instanceof Array?c:ca(ba(c)));window.open(a,"Sign In",f.join(","))};var U=".LinkedInButton {\n  background: #0077B5;\n  display: table;\n  border-radius: 3px;\n  font-family: Helvetica Neue,Helvetica,Arial,sans-serif;\n  text-decoration: none;\n  color: white;\n  cursor: pointer;\n}\n.LinkedInButton .LinkedInIn {\n  font-family: 'Myriad Pro', 'Gill Sans', 'Gill Sans MT', Calibri, sans-serif;\n  padding-left: 6px;\n  padding-right: 5px;\n  border-right: 1px solid #0369A0;\n  border-radius: 3px;\n  font-weight: 600;\n  background: #0077B5;\n  display: table-cell;\n  vertical-align: middle;\n}\n.LinkedInButton .LinkedInText {\n  padding-left: .5em;\n  padding-right: .5em;\n  font-size: smaller;\n  display: table-cell;\n  vertical-align: middle;\n}";
U=void 0===U?"":U;if(document){var ya=document.head,V=document.createElement("style");V.type="text/css";V.styleSheet?V.styleSheet.cssText=U:V.appendChild(document.createTextNode(U));ya.appendChild(V)};function za(a){var b=void 0===a.size?"medium":a.size,c=a.host,e=void 0===a.$?"/linkedin":a.$,d;"medium"==b?d=1.5:"large"==b&&(d=2);return H("a",{onClick:function(f){f.preventDefault();xa(""+c+e);return!1},onMouseOver:function(f){f.currentTarget.style.background="#0369A0"},onMouseOut:function(f){f.currentTarget.style.background="#0077B5"},className:"LinkedInButton"},H("div",{style:"font-size:"+d+"rem;",className:"LinkedInIn"},"in"),H("div",{className:"LinkedInText"},"Sign In With LinkedIn"))};function Aa(a,b,c){function e(){var p=[],m=[],n={},k;g.getAllResponseHeaders().replace(/^(.*?):[^\S\n]*([\s\S]*?)$/gm,function(v,x,z){p.push(x=x.toLowerCase());m.push([x,z]);k=n[x];n[x]=k?k+","+z:z});return{ok:2==(g.status/100|0),status:g.status,statusText:g.statusText,url:g.responseURL,clone:e,text:function(){return g.responseText},json:function(){return JSON.parse(g.responseText)},blob:function(){return new Blob([g.response])},headers:{keys:function(){return p},entries:function(){return m},get:function(v){return n[v.toLowerCase()]},
has:function(v){return v.toLowerCase()in n}}}}c=void 0===c?{}:c;var d=void 0===c.headers?{}:c.headers,f=c.credentials,h=void 0===c.body?null:c.body,g=new XMLHttpRequest;g.open(void 0===c.method?"get":c.method,a,!0);for(var r in d)g.setRequestHeader(r,d[r]);g.withCredentials="include"==f;g.onload=function(){b(null,e())};g.onerror=function(){b("Could not load the resource at "+a+".")};g.send(h)};function Ba(a,b,c){Aa(a+"/signout",function(e,d){if(e)return c(e.message);e=d.json().error;c(e)},{method:"POST",headers:{ca:"application/json","Content-Type":"application/json"},body:JSON.stringify({W:b}),credentials:"include"})}
function Ca(a){var b=a.aa,c=b.ha,e=b.ja,d=a.W,f=void 0===a.L?function(){}:a.L,h=a.host;return H("div",{},H("img",{src:b.la,width:"50"}),"Hello, ",c," ",e,"!",H("a",{onClick:function(g){g.preventDefault();Ba(h,d,function(r){r?alert("Could not sign out: "+r+". Please refresh the page and try again. Alternatively, clear your cookies."):f()});return!1},href:"#"},"Sign Out"))};function W(){T.call(this);this.state={u:!0,error:null,g:{}};this.h=this.h.bind(this);window.addEventListener("message",this.h,!1)}var Y=T;W.prototype=da(Y.prototype);W.prototype.constructor=W;if(D)D(W,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var Da=Object.getOwnPropertyDescriptor(Y,Z);Da&&Object.defineProperty(W,Z,Da)}else W[Z]=Y[Z];W.h=Y.prototype;W.prototype.H=function(){this.g()};
W.prototype.g=function(){var a=this;this.i({u:!0});Aa(this.b.host+"/user",function(b,c){a.i({u:!1});if(b)return a.i({error:b});b=c.json();a.i({g:b})},{credentials:"include"})};W.prototype.h=function(a){a.origin==this.b.host&&"linkedin-signedin"==a.data&&this.g()};W.prototype.I=function(){window.removeEventListener("message",this.h)};
W.prototype.o=function(){var a=this;return this.state.error?H("div",{},"Error: ",this.state.error):this.state.u?H("div",{},"Loading..."):this.state.g.aa?H("div",{},H("button",{onClick:function(){var b="/update.js?ts="+(new Date).getTime(),c=document.createElement("script");c.type="module";c.src=b;document.body.appendChild(c)}},"Update"),H("button",{onClick:function(){debugger}},"Test"),H(Ca,Object.assign({},this.state.g,{L:function(){a.i({g:{}})},host:this.b.host}))):H("div",{},H(za,{host:this.b.host}))};
window.comments=function(a){var b=void 0===a.V?"preact":a.V;a=H(W,{host:void 0===a.host?"https://technation.sucks":a.host});sa(void 0,a,{},!1,document.getElementById(b),!1)};

//# sourceMappingURL=comments.js.map